package com.bakjoul.mareu.ui;

public enum MeetingViewEvent {
    DISPLAY_CREATE_MEETING,
    DISPLAY_ROOM_FILTER,
    DISPLAY_DATE_FILTER,
    DISPLAY_CREATE_MEETING_DATE_PICKER,
    DISPLAY_CREATE_MEETING_START_PICKER,
    DISPLAY_CREATE_MEETING_END_PICKER,
    DISPLAY_OVERLAPPING_MEETING_TOAST
}
