package com.bakjoul.mareu.ui;

public enum MeetingViewEvent {
    DISPLAY_CREATE_MEETING_DIALOG,
    DISPLAY_ROOM_FILTER_DIALOG,
    DISPLAY_DATE_FILTER_DIALOG,
    DISPLAY_CREATE_MEETING_DATE_PICKER,
    DISPLAY_CREATE_MEETING_START_PICKER,
    DISPLAY_CREATE_MEETING_END_PICKER,
    DISPLAY_OVERLAPPING_MEETING_TOAST,
    DISMISS_CREATE_MEETING_DIALOG
}
