package com.bakjoul.mareu.ui;

public enum MeetingViewEvent {
    DISPLAY_ROOM_FILTER_DIALOG,
    DISPLAY_DATE_FILTER_DIALOG,
    DISPLAY_CREATE_MEETING_DIALOG,
    DISMISS_CREATE_MEETING_DIALOG,
    DISPLAY_CREATE_MEETING_DATE_PICKER,
    DISPLAY_CREATE_MEETING_START_PICKER,
    DISPLAY_CREATE_MEETING_END_PICKER,
    DISPLAY_CREATE_MEETING_OVERLAPPING_TOAST,
    DISPLAY_CREATE_MEETING_START_TIME_PASSED_TOAST,
    DISPLAY_CREATE_MEETING_START_TIME_LIMIT,
    DISPLAY_CREATE_MEETING_MINIMUM_DURATION_TOAST,
    DISPLAY_CREATE_MEETING_MAXIMUM_DURATION_TOAST
}
